spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vipinkumar99/microservice-demo
          search-paths:
          -  payment-service
        default-label: master 